//
// Created by chen on 2022/9/12.
//
#include <syslog.h>

int main() {
    const char *program_name = "logtest";
    openlog("LOG_TEST", LOG_CONS | LOG_PID, 0);
    syslog(LOG_INFO,
           "This is a syslog test message generated by program \"%s\"\n",
           program_name);
    closelog();
    return 0;
}